name: Push API specification to marketplace

on: 
  release:
    types: [published]

jobs:
  copy-file:
    runs-on: ubuntu-24.04
    container:
      image: redocly/cli
    steps:      
    - name: Checkout source repo
      uses: actions/checkout@v4
      
    - name: Checkout destination repo
      uses: actions/checkout@v4
      with:
        repository: FRIDA-api/marketplace
        token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
        path: destination-repo

    - name: Resolve yaml references
      run: |
        mkdir -p tmp
        # Loop through all YAML files and bundle them
        for file in *.yaml; do
          redocly bundle "$file" --output "tmp/$(basename "$file")"
        done

    - name: Copy files
      run: |
        mkdir -p destination-repo/marketplace/src/assets/api
        # Loop over bundled YAML files and copy each to destination repo
        for file in tmp/*.yaml; do
          cp -f "$file" destination-repo/marketplace/src/assets/api/$(basename "$file")
        done

        cd destination-repo

        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add .

        if git status | grep -q "Changes to be committed"; then
          git commit -m "Copy api specifications" --allow-empty
          git push origin main
        else
          echo "No changes detected"
        fi
